pipeline {
    agent {
        label "agent-1"
        }
    environment {
        REGION = "us-east-1"
        ACC_ID = "127218179061"
        PROJECT = "roboshop"
        COMPONENT = "catalogue"
    }        

    stages{
        stage("init"){
            steps{
                script{
                    withAWS(credentials: 'aws-cred', region: 'us-east-1'){
                        sh """ 
                        cd terraform-eks/eks
                          terraform init --reconfigure
                        """
                    }
                }
            }
        }

        stage("plan"){
            steps{
                script{
                    withAWS(credentials: 'aws-cred', region: 'us-east-1'){
                        sh """ 
                          cd terraform-eks/eks
                          terraform plan -lock=false
                        """ 
                      }
                }
            }
        }

        stage("apply"){
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
            }

            steps{
                script{
                    withAWS(credentials: 'aws-cred', region: 'us-east-1'){
                    sh """
                        cd terraform-eks/eks
                        terraform apply -auto-approve -lock=false
                    """
                    }
                }
            }
        }
    }

    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'Hello Success'
        }
        failure { 
            echo 'Hello Failure'
        }
    }

}