apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis
      tier: database
      project: roboshop 
  template:
    metadata:
      name: redis
      labels:
        component: redis
        tier: database
        project: roboshop 
    spec:
      containers:
        - name: redis
          image: redis:7.0
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:  
  selector:
    component: redis
    tier: database
    project: roboshop  
  ports:
  - protocol: TCP
    targetPort: 6379  
    port: 6379

