apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: "testing-taint-concept"
    project: roboshop
spec:
  containers:
    - name: nginx
      image: nginx     
  nodeSelector:
    project: "roboshop"     
