apiVersion: v1 
kind: Secret
metadata:
  name: mysql
  namespace: roboshop
type: Opaque  
data:
  MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ=="

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql
      project: roboshop
      tier: database        
  template:
    metadata:
      name: mysql
      namespace: roboshop
      labels:
        component: mysql
        project: roboshop
        tier: database
    spec:
      containers:
        - name: mysql
          image: dd070/mysql:v2
          envFrom:
            - secretRef:
                name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:                          
  selector:
    component: mysql
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      targetPort: 3306
      port: 3306  
