apiVersion: v1
kind: Pod
metadata:
  name: pods-configmap
  annotations:
    purpose: referencing configmap file to pods
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: configmap       