apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
        component: shipping
        project: roboshop
        tier: backend  
  template:
    metadata:
      name: shipping
      labels:
        component: shipping
        project: roboshop
        tier: backend  
    spec:
      containers:
        - name: shipping
          image: dd070/shipping:v2
          envFrom:
            - configMapRef:
                name: shipping
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
    component: shipping
    project: roboshop
    tier: backend 
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080    

