apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue" 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    component: catalogue
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      component: catalogue
      tier: database
      project: roboshop
  template:
    metadata:
      name: catalogue
      labels:
        component: catalogue
        tier: database
        project: roboshop
    spec:
      containers:
        - name: catalogue
          image: dd070/catalogue:v2

---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
      component: catalogue
      tier: database
      project: roboshop     
  ports:
   - protocol: TCP
     targetPort: 8080
     port: 8080     

